services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: n8n_ocr
    restart: unless-stopped
    ports:
      - "127.0.0.1:5678:5678"
    environment:
      - GENERIC_TIMEZONE=Europe/Moscow
      - TZ=Europe/Moscow
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}docker compose up -d
      - WEBHOOK_URL=https://${NGROK_DOMAIN}
      - N8N_BLOCK_ENV_ACCESS_IN_NODE=false
    volumes:
      - ./n8n_data:/home/node/.n8n
    networks:
      - ocr_net

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok_tunnel
    restart: unless-stopped
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    command: "http --domain=${NGROK_DOMAIN} n8n:5678"
    networks:
      - ocr_net
    depends_on:
      - n8n

networks:
  ocr_net:
    driver: bridge